name: flutter_shopping_cart
description: Flutter example of shopping app using Redux architecture

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_redux: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true